version: '3.3'
services:
  node-database:
    image: mysql:5.6
    ports:
      - 3316:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  node-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - node-database
    ports:
      - 800:80
    environment:
      - PMA_HOST=node-database
      - PMA_USER=root
      - PMA_PASSWORD=password
