version: '3.3'
services:
  node-database:
    image: mysql:5.6
    ports:
      - target: 3306
        published: 3316
        protocol: tcp
        mode: host
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    deploy:
      placement:
        constraints: [node.role == manager]
#    networks:
#      - solutisnet
  node-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - target: 80
        published: 800
        protocol: tcp
        mode: host
    environment:
      - PMA_HOST=node-database
      - PMA_USER=root
      - PMA_PASSWORD=password
    deploy:
      placement:
        constraints: [node.role == manager]
#    networks:
#      - solutisnet
  node-app:
    image: solutis-laravel:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: ingress
#    networks:
#      - solutisnet
#networks:
#  solutisnet:
